package com.blakdragon.petscapeclan.models.enums

import androidx.annotation.StringRes
import com.blakdragon.petscapeclan.R

enum class PetType(@StringRes val displayNameId: Int) {
    AbyssalOrphan(R.string.pet_abyssal_orphan),
    BabyMole(R.string.pet_baby_mole),
    CallistoCub(R.string.pet_callisto_cub),
    Hellpuppy(R.string.pet_hellpuppy),
    IkkleHydra(R.string.pet_ikkle_hydra),
    JalNibRek(R.string.pet_jal_nib_rek),
    KalphitePrincess(R.string.pet_kalphite_princess),
    LilZik(R.string.pet_lil_zik),
    LittleNightmare(R.string.pet_little_nightmare),
    Noon(R.string.pet_noon),
    Olmlet(R.string.pet_olmlet),
    PetChaosElemental(R.string.pet_chaos_elemental),
    PetDagannothPrime(R.string.pet_dagannoth_prime),
    PetDagannothRex(R.string.pet_dagannoth_rex),
    PetDagannothSupreme(R.string.pet_dagannoth_supreme),
    PetDarkCore(R.string.pet_dark_core),
    PetGeneralGraardor(R.string.pet_general_graardor),
    PetKrilTsutsaroth(R.string.pet_kril_tsutsaroth),
    PetKraken(R.string.pet_kraken),
    PetKreeArra(R.string.pet_kree_arra),
    PetSmokeDevil(R.string.pet_smoke_devil),
    PetSnakeling(R.string.pet_snakeling),
    PetZilyana(R.string.pet_zilyana),
    PrinceBlackDragon(R.string.pet_prince_black_dragon),
    ScorpiasOffspring(R.string.pet_scorpias_offspring),
    Skotos(R.string.pet_skotos),
    Sraracha(R.string.pet_sraracha),
    TzrekJad(R.string.pet_tzrek_jad),
    VenenatisSpiderling(R.string.pet_venenatis_spiderling),
    VetionJr(R.string.pet_vetion_jr),
    Vorki(R.string.pet_vorki),

    BabyChinchompa(R.string.pet_baby_chinchompa),
    Beaver(R.string.pet_beaver),
    GiantSquirrel(R.string.pet_giant_squirrel),
    Heron(R.string.pet_heron),
    RiftGuardian(R.string.pet_rift_guardian),
    RockGolem(R.string.pet_rock_golem),
    Rocky(R.string.pet_rocky),
    Tangleroot(R.string.pet_tangleroot),

    Bloodhound(R.string.pet_bloodhound),
    ChompyChick(R.string.pet_chompy_chick),
    Herbi(R.string.pet_herbi),
    LilCreator(R.string.pet_lil_creator),
    PetPenanceQueen(R.string.pet_penance_queen),
    Phoenix(R.string.pet_phoenix),
    TinyTempor(R.string.pet_tiny_tempor),
    Youngllef(R.string.pet_youngleff),
    Smolcano(R.string.pet_smolcano)
}
